server:
    port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test12
    username: root
    password: guswjd12

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      